export const MASCOT_SELECTORS = {
  root: '#mascot-root',
  shadow: '#mascot-shadow',
  stick: '#stick',
  torso: '#torso-group',
  body: '#body',
  frosting: '#frosting',
  sprinkles: '#sprinkles',
  leftEye: '#left-eye-container',
  rightEye: '#right-eye-container',
  leftPupil: '#left-pupil-group',
  rightPupil: '#right-pupil-group',
  leftEyebrow: '#left-eyebrow',
  rightEyebrow: '#right-eyebrow',
  mouth: '#mouth',
  leftCheek: '#left-cheek',
  rightCheek: '#right-cheek',
  leftArm: '#left-arm',
  rightArm: '#right-arm',
  leftFrontArm: '#left-arm-front',
  rightFrontArm: '#right-arm-front',
  leftLeg: '#left-leg',
  rightLeg: '#right-leg'
} as const;
